theme: jekyll-theme-minimal
title: Portfolio
description: Bookmark this to keep an eye on my project updates!

email: alexlam030@gmail.com
linkedin: https://www.linkedin.com/in/alexander-lam-053174139/
